
name: TestQA4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    Deploy:

        sourcePath = C:\AQ4test\

        destinationPath = C:\Test\

        # Define credentials for the destination server (in Domain B)
destinationCredentials = Get-Credential -Credential "us.hsi.local\USNYMEVHQA4"

Copy-Item -Path $sourcePath -Destination $destinationPath -ToSession $session

# Close the remote session

          Remove-PSSession $session
     
