name: TestQA4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployandtest :
   runs-on: windows-latest
 

         sourcePath = C:\AQ4test\
         destinationPath = C:\Test\
         destinationCredentials = Get-Credential -Credential "USNYMEVHQA4\USHSI\Manasa.Kotte"
         Copy-Item -Path $sourcePath -Destination $destinationPath -ToSession $session
        
     
