name: TestQA4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    Job:
    Deploy:

        sourcePath = C:\AQ4test\

        destinationPath = C:\Test\

            destinationCredentials = Get-Credential -Credential "USNYMEVHQA4\USHSI\Manasa.Kotte"

                  Copy-Item -Path $sourcePath -Destination $destinationPath -ToSession $session

                         Remove-PSSession $session
     
